services:
    app:
      image: ghcr.io/patrickuhlmann/cevi-int/quarkus:main
      volumes:
        - ./:/data
      environment:
        - QUARKUS_DATASOURCE_JDBC_URL=jdbc:sqlite:/data/international.db?journal_mode=wal
      restart: on-failure
      ports:
        - "9000:8080"